# Project: Evaluation of Postfix Expressions
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Chap03.5.o "Chap03.5-1\ stack\ operation.o" "Chap03.5-2\ get\ token\ function.o"
LINKOBJ  = Chap03.5.o "Chap03.5-1 stack operation.o" "Chap03.5-2 get token function.o"
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Evaluation of Postfix Expressions.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Chap03.5.o: Chap03.5.c
	$(CC) -c Chap03.5.c -o Chap03.5.o $(CFLAGS)

"Chap03.5-1\ stack\ operation.o": Chap03.5-1\ stack\ operation.c
	$(CC) -c "Chap03.5-1 stack operation.c" -o "Chap03.5-1 stack operation.o" $(CFLAGS)

"Chap03.5-2\ get\ token\ function.o": Chap03.5-2\ get\ token\ function.c
	$(CC) -c "Chap03.5-2 get token function.c" -o "Chap03.5-2 get token function.o" $(CFLAGS)
